# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2cb9e057c38b21fef5aa452eddd0b6e4"
name = "SBit - Image Compres and webp"
handle = "diversified-enterprise-app-13"
application_url = "https://computed-enabled-serves-kyle.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,write_files,read_themes,write_themes,"

[auth]
redirect_urls = [
  "https://computed-enabled-serves-kyle.trycloudflare.com/auth/callback",
  "https://computed-enabled-serves-kyle.trycloudflare.com/auth/shopify/callback",
  "https://computed-enabled-serves-kyle.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
