# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e8091ecf85154f7cd6717315c86263"
name = "Sbit: Image SEO Booster"
handle = "sbit-image-seo-booster"
application_url = "https://never-gras-bar-institutional.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,write_files,read_themes,write_themes,"

[auth]
redirect_urls = [
  "https://never-gras-bar-institutional.trycloudflare.com/auth/callback",
  "https://never-gras-bar-institutional.trycloudflare.com/auth/shopify/callback",
  "https://never-gras-bar-institutional.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
